name: dlc-webui-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.8
  - cudnn
  - ffmpeg
  - pip
  - pip:
    - streamlit
    - streamlit-authenticator
    - GPUtil
    - deeplabcut[tf,modelzoo]
    - numpy==1.24.3
    - pandas==2.0.3
    - pillow==10.0.1
    - opencv-python==4.8.1.78
    - scikit-learn==1.3.1
    - pyyaml==6.0.1
    - psutil==5.9.6
    - tqdm==4.66.1
    - scipy==1.10.1
    - matplotlib==3.7.5
    - seaborn==0.13.0
    - black==23.9.1
    - isort==5.12.0
    - pytest==7.4.2
    - pytest-cov==4.1.0
    - flake8 